#!/usr/bin/env python3
"""
Stub materializer:
Converts approved proposals into real, non-placeholder patch content.
This is NOT AI — it exists to unblock the pipeline and enforce contracts.
"""

from __future__ import annotations
import argparse, json
from pathlib import Path
from datetime import datetime, timezone
import sys

def die(msg: str, code: int = 2):
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(code)

def load_json(p: Path) -> dict:
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception as e:
        die(f"Invalid JSON: {p} ({e})")

def main() -> None:
    ap = argparse.ArgumentParser(prog="rf_materialize_stub")
    ap.add_argument("--app", required=True)
    ap.add_argument("--root", default="~/secondbrain")
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    app = Path(args.app).expanduser().resolve()
    pipe = app / "resume_refs" / "resume_pipeline"

    approvals_p = pipe / "approvals.json"
    proposals_p = pipe / "proposed-changes.md"
    patches_p = pipe / "patches.json"

    if not approvals_p.exists():
        die("approvals.json not found — nothing to materialize")

    approvals = load_json(approvals_p)
    approved_nums = approvals.get("approved_change_numbers", [])
    if not approved_nums:
        die("No approved_change_numbers in approvals.json")

    if patches_p.exists() and not args.force:
        die("patches.json already exists (use --force to overwrite)")

    # Minimal deterministic text generation
    patches = {
        "schema": "rf_patches_v1",
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "approved_change_numbers": approved_nums,
        "patches": []
    }

    for n in approved_nums:
        patches["patches"].append({
            "num": n,
            "text_lines": [
                f"[STUB CONTENT] Approved change #{n}.",
                "This content was generated by rf_materialize_stub.",
                "Replace this with AI-generated content later."
            ]
        })

    patches_p.write_text(json.dumps(patches, indent=2), encoding="utf-8")
    print(str(patches_p))

if __name__ == "__main__":
    main()
